# Generated by Django 5.0.4 on 2026-09-13 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ชื่อโรงเรียน")),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ตัวย่อชื่อโรงเรียน"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="ที่อยู่"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_level", models.CharField(max_length=5, verbose_name="ชั้นปี")),
                ("room_number", models.CharField(max_length=10, verbose_name="ทับ")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom",
                        to="apis.school",
                    ),
                ),
            ],
            options={
                "ordering": ["school", "grade_level", "room_number"],
                "unique_together": {("school", "grade_level", "room_number")},
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="ชื่อ")),
                ("last_name", models.CharField(max_length=150, verbose_name="นามสกุล")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        verbose_name="เพศ",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="apis.classroom",
                        verbose_name="ห้องเรียน",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="ชื่อ")),
                ("last_name", models.CharField(max_length=150, verbose_name="นามสกุล")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        verbose_name="เพศ",
                    ),
                ),
                (
                    "classrooms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teachers",
                        to="apis.classroom",
                        verbose_name="ห้องเรียน",
                    ),
                ),
            ],
        ),
    ]
