# Generated by Django 5.0.4 on 2026-09-13 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="room_number",
            field=models.CharField(max_length=10, verbose_name="ห้อง"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="apis.school",
            ),
        ),
    ]
